apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: secure-kubeflow
  namespace: {{ .Values.control_plane.namespace }}
spec:
  host: kubeflow.apps.{{ .Values.base_domain }}
  port:
    targetPort: 9443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: kubeflow
