apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: ai-ml
spec:
  watermarkPercentage: 20
  nodeSelector:
    workload: ai-ml
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "ai-ml"
    effect: "NoSchedule"  