apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: proactive-node-autoscaling-pods
value: 0
globalDefault: false
description: "This priority class is the Priority class for Proactive Node Scaling."
