apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: kubeflow-namespace
spec:
  labelSelector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow-profile  
  templates:
  - objectTemplate: |
      apiVersion: maistra.io/v1
      kind: ServiceMeshMember
      metadata:
        name: default
        namespace: {{ printf "{{ .Name }}" }}
      spec:
        controlPlaneRef:
          namespace: {{ .Values.control_plane.namespace }}
          name: {{ .Values.control_plane.name }}
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-editor-nonroot
        namespace: {{ printf "{{ .Name }}" }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:nonroot
      subjects:
      - kind: ServiceAccount
        name: default-editor
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-nonroot
        namespace: {{ printf "{{ .Name }}" }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:nonroot
      subjects:
      - kind: ServiceAccount
        name: default        
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-edit
        namespace: {{ printf "{{ .Name }}" }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        name: default        
  - objectTemplate: |          
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: default-resources
        namespace: {{ printf "{{ .Name }}" }}
      spec:
        limits:
        - defaultRequest:
            cpu: 0.2
            memory: 100Mi
          type: Container   
  - objectTemplate: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-from-serving-system-namespace
        namespace: {{ printf "{{ .Name }}" }}
      spec:
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                serving.knative.openshift.io/system-namespace: "true"
        podSelector: {}
        policyTypes:
        - Ingress                   
