apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: ai-ml-toleration-injection
spec:
  match:
    scope: Cluster
    kinds:
      - apiGroups: 
        - ''
        kinds: 
        - Namespace                                    
  location: "metadata.annotations.'scheduler.alpha.kubernetes.io/defaultTolerations'"
  parameters:
    assign:
      value: '[{"operator": "Equal", "effect": "NoSchedule", "key": "workload", "value": "ai-ml"}]'